# Published install is the Homebrew cask in francistse/homebrew-tap
# (brew install --cask francistse/tap/deployboard), generated by GoReleaser
# on each tagged release. See docs/RELEASE.md.
#
# This formula is a local/dev source-build helper only:
#   brew install --build-from-source ./Formula/deployboard.rb
# Prefer the cask or install.sh / install-release.sh for real installs.

class Deployboard < Formula
  desc "Deployboard: launchd inventory + Prometheus metrics + Telegram alerts"
  homepage "https://github.com/francistse/deployboard"
  url "https://github.com/francistse/deployboard/archive/refs/tags/v0.0.2.tar.gz"
  version "0.0.2"
  license "MIT"
  head "https://github.com/francistse/deployboard.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.Version=#{version}"),
           "./cmd/deployboard"
  end

  service do
    run [opt_bin/"deployboard", "--config", etc/"deployboard/config.json"]
    run_type :immediate
    keep_alive true
    log_path var/"log/deployboard.log"
    error_log_path var/"log/deployboard.log"
    environment_variables PATH: std_service_path_env
  end

  def caveats
    <<~EOS
      This in-repo formula builds from source for development. For the published
      binary install use:
        brew install --cask francistse/tap/deployboard
      or:
        curl -fsSL https://raw.githubusercontent.com/francistse/deployboard/main/install-release.sh | bash

      To enable Telegram alerts, store the bot token in the macOS Keychain:
        security add-generic-password -U -s deployboard-telegram -a bot_token -w "$TOKEN" -T /usr/bin/security
    EOS
  end

  test do
    assert_match "deployboard", shell_output("#{bin}/deployboard --version")
  end
end
