import type { Content } from "./types";
import { REPO, heroPanel, logStream, metricsQuery, metricsSample } from "./fixtures";

export const content: Content = {
  meta: {
    title: "Deployboard — see your own launchd deployments, not 500 system jobs",
    description:
      "A local dashboard for the launchd jobs you actually deployed: what is running, what broke, what you retired on purpose — plus Prometheus metrics and Telegram alerts with per-application toggles. Binds to 127.0.0.1; no cloud, no telemetry.",
  },
  brand: {
    name: "Deployboard",
    mark: "DB",
    tagline: "your launchd deployments, legible",
    installCommand: "brew install --cask francistse/tap/deployboard",
    launchCommand: "deployboard",
    github: "github.com/francistse/deployboard",
    githubUrl: REPO,
    changelogUrl: REPO + "/blob/main/CHANGELOG.md",
    upstreamUrl: "https://github.com/RoboZephyr/launch-pilot",
    version: "v0.0.2",
    license: "MIT",
  },
  nav: [
    { label: "Why", href: "#why" },
    { label: "Ours", href: "#ours" },
    { label: "Metrics", href: "#metrics" },
    { label: "Alerts", href: "#alerts" },
    { label: "Install", href: "#install" },
  ],
  ui: {
    skipToContent: "Skip to content",
    github: "GitHub",
    copy: "copy",
    copied: "copied",
    primaryNav: "Primary",
    language: "Language",
    settings: "Settings",
  },
  hero: {
    eyebrow: "v0.0.2 · MIT · macOS · fork of launch-pilot",
    headline: ["Your deployments,", "not 545 system jobs."],
    body: "Your Mac runs hundreds of LaunchAgents — Dropbox, Chrome, Spotify, every updater. Deployboard shows the ones you actually deployed, tells you which are up, which are broken, and which you retired on purpose. Then it turns all of it into Prometheus metrics and Telegram alerts.",
    primaryCta: { label: "Install in one command", href: "#install" },
    secondaryCta: { label: "Read the source", href: REPO },
    metaRow: [
      { key: "runtime", value: "Local · 127.0.0.1 only" },
      { key: "shows", value: "your apps · system noise hidden" },
      { key: "exposes", value: "/metrics · /api/jobs · SSE" },
    ],
  },
  livePanel: {
    title: "127.0.0.1:9410 · Deployboard",
    liveBadge: "SSE · live",
    appTagline: "macOS launchd inventory — your deployments only",
    badges: {
      alerts: "16 on · 2 off",
      inventory: "16 ours · 1 other · 528 noise",
      writeMode: "write mode",
      url: "http://127.0.0.1:9410",
    },
    searchPlaceholder: "Search labels…",
    noiseToggle: "Show system & vendor jobs",
    filters: { all: "All", ours: "Ours", noise: "Noise", other: "Other" },
    hiddenSuffix: " hidden",
    columns: ["Label", "PID", "Exit", "Runs", "Actions"],
    jobsSuffix: "jobs",
    nextRunPrefix: "next ·",
    retiredLabel: "⏹ retired 12d",
    churnLabel: "↻ churn",
    restartLoopLabel: "⚠ restart loop",
    actions: { restart: "Restart", start: "Start", enable: "Enable", logs: "Logs" },
    sourceLabels: { listed: "listed", path: "auto (path)", unclassified: "unclassified" },
    groupNames: { app: "Example App", ops: "Ops", infra: "Infra" },
    alertsOn: "Telegram alerts on",
    alertsOff: "Telegram alerts off",
    events: "GET /api/events",
    streamType: "text/event-stream",
    push: "5s push",
    ...heroPanel,
  },
  why: {
    eyebrow: "Why",
    headline: "launchctl lists everything, so you can see nothing.",
    paragraphs: [
      "The stock tools answer \"what is loaded\", never \"what did I deploy, and is it healthy\". A user-domain filter is no help either — on a working Mac most of what looks like \"your\" jobs is Dropbox, Google's updater, Spotify, Tailscale and a browser helper or two. The one job that has restarted 1,207 times is buried in the middle of it.",
      "Deployboard starts from an explicit inventory: an allowlist you control, plus path derivation — a job whose plist log path, working directory, program or arguments live inside your project tree is one of yours, automatically. Everything else is the system's business and stays one click away, never in the way.",
    ],
    contrast: {
      before: {
        label: "Without Deployboard",
        bullets: [
          "launchctl list — 545 rows, no idea which are yours",
          "A dev server that has silently restarted 1,207 times looks healthy",
          "A plist you disabled on purpose still reads as a failure",
          "No history: \"is this normal?\" has no answer",
          "You find out something died when you notice by accident",
        ],
      },
      after: {
        label: "With Deployboard",
        bullets: [
          "Ours / Other / Noise — your deployments first, by default",
          "runs (restart counter) from launchctl print, flagged past a threshold",
          "disabled is a status, not an error — retired means retired",
          "Prometheus /metrics so Grafana can show \"since when\"",
          "Telegram alerts on transitions, per application, with a cooldown",
        ],
      },
    },
  },
  statusSection: {
    eyebrow: "Statuses",
    title: "Seven values, and one of them means “I retired it”.",
    body: "Most tools collapse to running / stopped / error, and then a plist you switched off months ago reads as a failure forever. Deployboard keeps the distinctions launchd actually exposes — and reads launchctl print-disabled so intent is part of the answer.",
  },
  statusMeta: {
    running: "Running",
    scheduled: "Scheduled",
    completed: "Completed",
    stopped: "Stopped",
    error: "Error",
    offline: "Offline",
    disabled: "Disabled",
  },
  statuses: [
    { status: "running", rule: "PID > 0 — launchd print agrees it is alive" },
    { status: "scheduled", rule: "PID = 0, clean exit, schedule defined, no recent log" },
    { status: "completed", rule: "PID = 0, clean exit, log mtime inside --recent-window" },
    { status: "stopped", rule: "PID = 0, clean exit, no schedule, no recent log" },
    { status: "error", rule: "Last exit status non-zero" },
    { status: "disabled", rule: "launchctl print-disabled says disabled, no live pid — retired, not broken" },
    { status: "offline", rule: "plist file present, launchctl list does not return the label" },
  ],
  forkSection: {
    eyebrow: "What this fork adds",
    title: "Upstream answers “what is loaded”. This answers “what did I deploy”.",
    body: "Four additions, all of them built on launchctl's own output — no heuristics about which vendor a job belongs to.",
    upstreamLabel: "still here from upstream",
    keepers: [
      { name: "Log tail", body: "stdout + stderr per job, up to 10,000 lines, live-filtered." },
      { name: "Six diagnostics", body: "exit code, program exists, program executable, plist owner, plist permissions, log path." },
      { name: "SSE, not polling", body: "GET /api/events pushes the full job list every 5s." },
      { name: "One-click control", body: "start / stop / reload through launchctl, with a confirmation dialog." },
      { name: "JSON API", body: "the same surface the UI consumes, documented and curl-friendly." },
      { name: "Zero deps", body: "one Go binary, frontend embedded via go:embed, no daemon, no telemetry." },
    ],
  },
  forkAdditions: [
    {
      index: "01",
      title: "launchctl print, not launchctl list.",
      body: "launchctl list has no restart counter and no disabled flag. Deployboard reads launchctl print for runs and pid, and launchctl print-disabled for intent — so churn is visible and a deliberately retired job stops looking broken.",
      accent: "brand",
    },
    {
      index: "02",
      title: "An inventory you decide on.",
      body: "ours / other / noise, with provenance on every row (listed, auto (path), unclassified). The classify control writes back to config.json, which is hot-reloaded in ~2 seconds — no restart to teach it a new app.",
    },
    {
      index: "03",
      title: "Prometheus metrics for launchd.",
      body: "deployboard_job_up, _runs, _last_exit_code, _disabled plus IPv4/IPv6 port probes. A dashboard can only tell you \"down now\"; a time series tells you \"this started churning at 03:10\".",
      accent: "accent",
    },
    {
      index: "04",
      title: "Telegram alerts with per-app toggles.",
      body: "Transitions only — error, offline, port unreachable, restart storm, and recovery — with a per-application switch, a cooldown, quiet hours, and the bot token held in the macOS Keychain, never in a file.",
      accent: "warning",
    },
  ],
  logStream,
  stream: {
    eyebrow: "Live stream",
    headline: "Logs land in the browser as launchd writes them.",
    body: "Per-job stdout and stderr, tailed from the paths the plist declares and pushed over Server-Sent Events. Jobs with no port and no HTTP surface are still tracked — a collector with a cron schedule is part of the inventory even though there is nothing to probe.",
    badges: ["Server-Sent Events", "Per-job tail", "Up to 10,000 lines", "Live filter"],
    endpoint: "GET /api/events",
    endpointStatus: "streaming",
  },
  metrics: {
    eyebrow: "Metrics",
    headline: "The only launchd exporter in this niche.",
    body: "Point Prometheus at the same port the UI uses. Bounded label cardinality, honest omissions (no last-exit series for a job that never exited), probe series only for jobs that expose a port — and probes that try IPv6 ::1 too, because some dev servers bind there and nowhere else.",
    sampleLabel: "GET /metrics",
    queryLabel: "promql",
    footnoteBefore:
      "Scrape it from the same process that serves the UI — no exporter to deploy, no sidecar. Series are omitted rather than faked: a job that never exited gets no ",
    footnoteCode: "last_exit",
    footnoteAfter: " line, and a job with no port gets no probe line.",
    sample: metricsSample,
    query: metricsQuery,
  },
  alerts: {
    eyebrow: "Alerts",
    headline: "It tells you, once, on Telegram.",
    body: "Transition-based, so a flapping job cannot spam you: one message when it breaks, a rate-limited one if it keeps restarting, one when it comes back. Recovery is never suppressed by quiet hours. The bot token lives in the macOS Keychain and is written by the dashboard itself — never a file, never a log line, never returned to the page.",
    channel: "telegram · deployboard",
    triggerHeader: "trigger",
    kindHeader: "kind",
    footer:
      "Per-application switches, a cooldown, quiet hours, and recovery messages that quiet hours never swallow.",
    message: [
      "🔴 RUN_STORM",
      "Example App · com.example.app.web",
      "status: running",
      "restarts: 1207",
      "2026-10-03 10:41:07 +0800",
    ],
    rules: [
      { trigger: "status → error", kind: "error" },
      { trigger: "plist present, not loaded", kind: "offline" },
      { trigger: "port stopped answering", kind: "unreachable" },
      { trigger: "runs +25 between sweeps", kind: "run_storm" },
      { trigger: "back to running", kind: "recovery" },
    ],
  },
  api: {
    eyebrow: "API",
    title: "Everything the UI uses, also available to your scripts.",
    body: "The web UI is one consumer of /api/jobs and /api/events. So is curl. Bind the server, point at the endpoints, parse the JSON.",
    verb: "verb",
    path: "path",
    description: "description",
    endpoints: [
      { method: "GET", path: "/api/inventory", note: "category + group counts, and how each job was classified" },
      { method: "POST", path: "/api/inventory/classify", note: "pin a job as ours / hide it / back to auto" },
      { method: "GET", path: "/metrics", note: "Prometheus exposition — jobs, runs, exit codes, probes" },
      { method: "GET", path: "/api/jobs", note: "List every job, including offline plists" },
      { method: "GET", path: "/api/jobs/{label}", note: "Single-job snapshot (status, pid, runs, disabled)" },
      { method: "GET", path: "/api/alerts", note: "per-application alert state + enabled/disabled counts" },
      { method: "POST", path: "/api/alerts/{label}", note: 'toggle alerts: {"enabled": false}' },
      { method: "POST", path: "/api/alerts/{label}/test", note: "send one test alert for that job" },
      { method: "GET", path: "/api/settings/telegram", note: "token stored? chat id? — never the token itself" },
      { method: "GET", path: "/api/jobs/{label}/logs?lines=200", note: "Tail stdout + stderr (max 10,000)" },
      { method: "GET", path: "/api/events", note: "SSE stream — full job list pushed every 5s" },
      { method: "POST", path: "/api/jobs/{label}/reload", note: "launchctl bootout + bootstrap (403 in read-only mode)" },
    ],
  },
  steps: [
    {
      index: "01",
      title: "Install",
      body: "Homebrew cask for the binary, or curl install-release.sh / bash install.sh for a LaunchAgent with RunAtLoad + KeepAlive. No sudo; --dry-run and --uninstall included on the scripts.",
      command: "brew install --cask francistse/tap/deployboard",
    },
    {
      index: "02",
      title: "Point it at your apps",
      body: "Either list your namespaces under inventory.ours in config.json, or add your project folders to derive_roots and let the plist paths classify themselves. Anything unclassified shows up as Other — one click in the UI pins it, and config.json hot-reloads.",
      command: "open ~/.config/deployboard/config.json",
    },
    {
      index: "03",
      title: "Watch it, or scrape it",
      body: "The dashboard opens on 127.0.0.1. Scrape /metrics from Prometheus, toggle alerts per application with the bell, and switch the theme between System, Light and Dark.",
    },
  ],
  stats: [
    { value: "7", label: "status values", caption: "six from upstream + disabled" },
    { value: "2s", label: "config hot reload", caption: "no restart to classify a new app" },
    { value: "12", label: "Prometheus series families", caption: "jobs, runs, exit codes, probes" },
    { value: "127.0.0.1", label: "the only address it binds to", caption: "no cloud, no telemetry, no update ping" },
  ],
  faqSection: {
    eyebrow: "FAQ",
    title: "The questions a fork has to answer.",
    body: "Including the one about how this relates to upstream.",
  },
  faqs: [
    {
      question: "How is this different from launch-pilot, which it forks?",
      answer:
        "Everything upstream does is still here — the job table, log tail, six diagnostics, start/stop/reload. Deployboard adds the inventory view (ours/other/noise with path derivation), launchctl print enrichment (runs and disabled), a Prometheus endpoint, Telegram alerts with per-application toggles, read-only mode, and three install paths: Homebrew cask, GitHub Release binary (install-release.sh), and install.sh from a clone.",
    },
    {
      question: "How does it know which jobs are mine?",
      answer:
        "Two rules, in order: an explicit allowlist you write (inventory.ours), then derivation — if the plist's log path, working directory, program or arguments sit inside a directory you listed under derive_roots, the job is yours. Everything the plist points at is evidence, so no guessing and no domain heuristics.",
    },
    {
      question: "What if it gets a job wrong?",
      answer:
        "It shows up as Other, tagged \"unclassified\", and you pick Auto / Ours / Hide from the row. That writes config.json, which the server hot-reloads in about two seconds. Nothing is hidden silently: the full launchd list is always one chip away.",
    },
    {
      question: "Does any of this leave my machine?",
      answer:
        "No. The HTTP server binds to 127.0.0.1 only, there is no analytics or phone-home, and the only outbound call the whole project can make is a Telegram message you explicitly enabled — using a token stored in your own Keychain.",
    },
    {
      question: "Can I use it only for metrics, without the alerts?",
      answer:
        "Yes. Alerts default to on for your own apps and off for everything else; disable them per application, per category, or entirely. /metrics and the JSON API keep working regardless, and --read-only refuses every mutating call.",
    },
    {
      question: "Why does it never edit my plists?",
      answer:
        "Deliberately. Deployboard reads launchd state and can ask launchctl to start, stop or reload a label, but it will not rewrite a plist on disk. If you want a plist editor, LaunchControl is the established paid option; this tool is about knowing what your deployments are doing.",
    },
  ],
  install: {
    eyebrow: "Install",
    title: "One command. One config file. One tab.",
    body: "Three supported installs, same binary: Homebrew cask (hero command), curl install-release.sh for a LaunchAgent without Go, or bash install.sh from a clone. No sudo; scripts support --dry-run and --uninstall.",
  },
  cta: {
    eyebrow: "Install",
    headline: "Know what your Mac is running.",
    body: "brew install --cask francistse/tap/deployboard — or curl the release installer if you are not on Homebrew. One config file to mark what is yours.",
    command: "brew install --cask francistse/tap/deployboard",
  },
  footer: {
    copyline: "© 2026 Deployboard — MIT licensed, fork of RoboZephyr/launch-pilot",
    links: [
      { label: "GitHub", href: REPO },
      { label: "Upstream", href: "https://github.com/RoboZephyr/launch-pilot" },
      { label: "Metrics guide", href: REPO + "/blob/main/docs/METRICS.md" },
      { label: "Alerts guide", href: REPO + "/blob/main/docs/ALERTS.md" },
      { label: "launchd(8)", href: "https://keith.github.io/xcode-man-pages/launchd.8.html" },
    ],
  },
};
