import type { Content } from "./types";
import { REPO, heroPanel, logStream, metricsQuery, metricsSample } from "./fixtures";

export const content: Content = {
  meta: {
    title: "Deployboard — 500 個のシステムジョブではなく、自分の launchd デプロイを見る",
    description:
      "実際にデプロイした launchd ジョブのためのローカルダッシュボードです。動いているもの、壊れたもの、意図して退役させたものが分かり、Prometheus メトリクスと、アプリごとに切り替えられる Telegram 通知も付きます。127.0.0.1 にだけバインドし、クラウドもテレメトリもありません。",
  },
  brand: {
    name: "Deployboard",
    mark: "DB",
    tagline: "あなたの launchd デプロイを、読める形に",
    installCommand: "brew install --cask francistse/tap/deployboard",
    launchCommand: "deployboard",
    github: "github.com/francistse/deployboard",
    githubUrl: REPO,
    changelogUrl: REPO + "/blob/main/CHANGELOG.md",
    upstreamUrl: "https://github.com/RoboZephyr/launch-pilot",
    version: "v0.0.2",
    license: "MIT",
  },
  nav: [
    { label: "理由", href: "#why" },
    { label: "追加", href: "#ours" },
    { label: "メトリクス", href: "#metrics" },
    { label: "アラート", href: "#alerts" },
    { label: "インストール", href: "#install" },
  ],
  ui: {
    skipToContent: "本文へスキップ",
    github: "GitHub",
    copy: "コピー",
    copied: "コピー済み",
    primaryNav: "メイン",
    language: "言語",
    settings: "設定",
  },
  hero: {
    eyebrow: "v0.0.2 · MIT · macOS · launch-pilot のフォーク",
    headline: ["あなたのデプロイだけ。", "545 個のシステムジョブではない。"],
    body: "Mac では Dropbox、Chrome、Spotify、あらゆるアップデータなど、何百もの LaunchAgents が動いています。Deployboard は、実際にデプロイしたものだけを見せ、動いているもの、壊れているもの、意図して退役させたものを分けます。そのうえで全体を Prometheus メトリクスと Telegram 通知にします。",
    primaryCta: { label: "コマンド一つで導入", href: "#install" },
    secondaryCta: { label: "ソースを読む", href: REPO },
    metaRow: [
      { key: "実行場所", value: "ローカル · 127.0.0.1 のみ" },
      { key: "表示", value: "自分のアプリ · システムのノイズは隠す" },
      { key: "公開", value: "/metrics · /api/jobs · SSE" },
    ],
  },
  livePanel: {
    title: "127.0.0.1:9410 · Deployboard",
    liveBadge: "SSE · ライブ",
    appTagline: "macOS launchd インベントリ — 自分のデプロイだけ",
    badges: {
      alerts: "16 オン · 2 オフ",
      inventory: "自前 16 · その他 1 · ノイズ 528",
      writeMode: "書き込みモード",
      url: "http://127.0.0.1:9410",
    },
    searchPlaceholder: "ラベルを検索…",
    noiseToggle: "システムとベンダーのジョブを表示",
    filters: { all: "すべて", ours: "自前", noise: "ノイズ", other: "その他" },
    hiddenSuffix: " 件を非表示",
    columns: ["ラベル", "PID", "終了", "再起動", "操作"],
    jobsSuffix: "件",
    nextRunPrefix: "次回 ·",
    retiredLabel: "⏹ 退役 12日",
    churnLabel: "↻ 再起動多発",
    restartLoopLabel: "⚠ 再起動ループ",
    actions: { restart: "再起動", start: "開始", enable: "有効化", logs: "ログ" },
    sourceLabels: { listed: "記載あり", path: "自動（パス）", unclassified: "未分類" },
    groupNames: { app: "サンプルアプリ", ops: "運用", infra: "基盤" },
    alertsOn: "Telegram 通知オン",
    alertsOff: "Telegram 通知オフ",
    events: "GET /api/events",
    streamType: "text/event-stream",
    push: "5秒ごとに配信",
    ...heroPanel,
  },
  why: {
    eyebrow: "理由",
    headline: "launchctl は全部出す。だから、何も見えない。",
    paragraphs: [
      "標準のツールが答えるのは「何が読み込まれているか」であり、「何をデプロイし、それは健全か」ではありません。ユーザードメインで絞り込んでも同じです。動いている Mac では、「自分の」ジョブに見えるものの大半が Dropbox、Google のアップデータ、Spotify、Tailscale、ブラウザのヘルパーです。1,207 回再起動しているジョブは、その真ん中に埋まっています。",
      "Deployboard は、明示的な台帳から始めます。自分で書く許可リストと、パスからの導出です。plist のログパス、作業ディレクトリ、program、引数のいずれかがプロジェクトツリーの中にあれば、そのジョブは自動的に自分のものです。それ以外はシステムの用事であり、ワンクリックで届きますが、邪魔にはしません。",
    ],
    contrast: {
      before: {
        label: "Deployboard なし",
        bullets: [
          "launchctl list — 545 行。どれが自分のものか分からない",
          "静かに 1,207 回再起動した開発サーバーが、正常に見える",
          "意図して無効にした plist が、いつまでも障害に見える",
          "履歴がない。「これは平常か？」に答えがない",
          "何かが死んだことに、偶然気づくまで分からない",
        ],
      },
      after: {
        label: "Deployboard あり",
        bullets: [
          "自前 / その他 / ノイズ — 初期表示は自分のデプロイ",
          "launchctl print の runs（再起動回数）。閾値を超えると印が付く",
          "disabled は状態であり、エラーではない。退役は退役のまま",
          "Prometheus の /metrics。Grafana で「いつから」が見える",
          "遷移のときに Telegram 通知。アプリごと、クールダウン付き",
        ],
      },
    },
  },
  statusSection: {
    eyebrow: "状態",
    title: "状態は七つ。その一つは「自分で退役させた」。",
    body: "多くのツールは running / stopped / error に潰してしまいます。すると、何ヶ月も前に自分で止めた plist が、永遠に障害として表示されます。Deployboard は launchd が実際に区別している状態を保ち、launchctl print-disabled を読むので、意図も答えの一部になります。",
  },
  statusMeta: {
    running: "実行中",
    scheduled: "スケジュール済み",
    completed: "完了",
    stopped: "停止",
    error: "エラー",
    offline: "オフライン",
    disabled: "無効",
  },
  statuses: [
    { status: "running", rule: "PID > 0 — launchd print も生存に同意している" },
    { status: "scheduled", rule: "PID = 0、正常終了、スケジュールあり、直近のログなし" },
    { status: "completed", rule: "PID = 0、正常終了、ログの mtime が --recent-window 以内" },
    { status: "stopped", rule: "PID = 0、正常終了、スケジュールなし、直近のログなし" },
    { status: "error", rule: "直前の終了ステータスが非ゼロ" },
    { status: "disabled", rule: "launchctl print-disabled が disabled、生きている pid はない — 退役であり、故障ではない" },
    { status: "offline", rule: "plist ファイルはあるが、launchctl list がラベルを返さない" },
  ],
  forkSection: {
    eyebrow: "このフォークが足すもの",
    title: "本家が答えるのは「何が読み込まれているか」。こちらが答えるのは「何をデプロイしたか」。",
    body: "追加は四つ。どれも launchctl 自身の出力の上に乗せてあり、ジョブがどのベンダーのものかを推測しません。",
    upstreamLabel: "本家から、そのまま残しているもの",
    keepers: [
      { name: "ログの追尾", body: "ジョブごとの stdout と stderr。最大 10,000 行、ライブで絞り込めます。" },
      { name: "六つの診断", body: "終了コード、program の存在、実行権限、plist の所有者、plist のパーミッション、ログパス。" },
      { name: "SSE。ポーリングではない", body: "GET /api/events が、ジョブ一覧全体を 5 秒ごとに送ります。" },
      { name: "ワンクリック操作", body: "launchctl 経由の start / stop / reload。確認ダイアログ付きです。" },
      { name: "JSON API", body: "UI が使っているのと同じ面。文書化されていて、curl で触れます。" },
      { name: "依存ゼロ", body: "Go のバイナリ一つ。フロントは go:embed。常駐デーモンもテレメトリもありません。" },
    ],
  },
  forkAdditions: [
    {
      index: "01",
      title: "launchctl print を使う。launchctl list ではない。",
      body: "launchctl list には再起動回数も disabled フラグもありません。Deployboard は runs と pid を launchctl print から、意図を launchctl print-disabled から読みます。回転が見え、意図して退役させたジョブが故障に見えなくなります。",
      accent: "brand",
    },
    {
      index: "02",
      title: "台帳は、自分で決める。",
      body: "自前 / その他 / ノイズ。各行に出処があります（記載あり、自動（パス）、未分類）。分類の操作は config.json に書き戻され、約 2 秒でホットリロードされます。新しいアプリを教えるのに再起動は要りません。",
    },
    {
      index: "03",
      title: "launchd のための Prometheus メトリクス。",
      body: "deployboard_job_up、_runs、_last_exit_code、_disabled に加え、IPv4/IPv6 のポートプローブがあります。ダッシュボードが言えるのは「今落ちている」までです。時系列なら「03:10 から回転し始めた」と言えます。",
      accent: "accent",
    },
    {
      index: "04",
      title: "アプリごとの切替が付いた Telegram 通知。",
      body: "通知するのは遷移だけです。error、offline、ポート到達不能、再起動ストーム、そして復旧。アプリごとのスイッチ、クールダウン、静音時間があり、ボットのトークンは macOS のキーチェーンに置きます。ファイルには書きません。",
      accent: "warning",
    },
  ],
  logStream,
  stream: {
    eyebrow: "ライブストリーム",
    headline: "launchd が書いたログが、そのままブラウザに届きます。",
    body: "ジョブごとの stdout と stderr を、plist が宣言したパスから追尾し、Server-Sent Events で送ります。ポートも HTTP 面もないジョブも追跡します。cron スケジュールのコレクターは、プローブする先がなくても台帳の一部です。",
    badges: ["Server-Sent Events", "ジョブごとの追尾", "最大 10,000 行", "ライブ絞り込み"],
    endpoint: "GET /api/events",
    endpointStatus: "配信中",
  },
  metrics: {
    eyebrow: "メトリクス",
    headline: "この領域で、唯一の launchd exporter。",
    body: "Prometheus には、UI と同じポートを向けてください。ラベルのカーディナリティは有界です。一度も終了していないジョブに last-exit の系列は出さず、ポートを公開しているジョブにだけ probe の系列を出します。一部の開発サーバーは IPv6 の ::1 にしかバインドしないため、プローブはそこも試します。",
    sampleLabel: "GET /metrics",
    queryLabel: "promql",
    footnoteBefore:
      "UI を配信しているのと同じプロセスからスクレイプできます。別の exporter も sidecar も要りません。出せない系列は省き、値は作りません。一度も終了していないジョブに ",
    footnoteCode: "last_exit",
    footnoteAfter: " の行はなく、ポートのないジョブに probe の行はありません。",
    sample: metricsSample,
    query: metricsQuery,
  },
  alerts: {
    eyebrow: "アラート",
    headline: "Telegram に、一度だけ知らせます。",
    body: "遷移ベースなので、フラッピングするジョブが通知を埋め尽くすことはありません。壊れたときに一通、再起動が続くときはレート制限された一通、戻ったときに一通です。復旧の通知は静音時間でも抑止しません。ボットのトークンは macOS のキーチェーンにあり、ダッシュボード自身が書き込みます。ファイルにも、ログ行にも、ページの応答にも出しません。",
    channel: "telegram · deployboard",
    triggerHeader: "きっかけ",
    kindHeader: "種別",
    footer: "アプリごとのスイッチ、クールダウン、静音時間。復旧メッセージは静音時間に飲み込まれません。",
    message: [
      "🔴 RUN_STORM",
      "Example App · com.example.app.web",
      "状態: 実行中",
      "再起動: 1207",
      "2026-10-03 10:41:07 +0800",
    ],
    rules: [
      { trigger: "状態が error になる", kind: "error" },
      { trigger: "plist はあるが未ロード", kind: "offline" },
      { trigger: "ポートが応答をやめた", kind: "unreachable" },
      { trigger: "走査のあいだに runs が +25", kind: "run_storm" },
      { trigger: "running に戻った", kind: "recovery" },
    ],
  },
  api: {
    eyebrow: "API",
    title: "UI が使っているものは、スクリプトからも使えます。",
    body: "Web UI は /api/jobs と /api/events の利用者の一つです。curl も同じです。サーバーをバインドし、エンドポイントを向き、JSON を解析してください。",
    verb: "メソッド",
    path: "パス",
    description: "説明",
    endpoints: [
      { method: "GET", path: "/api/inventory", note: "カテゴリとグループの件数、および各ジョブの分類方法" },
      { method: "POST", path: "/api/inventory/classify", note: "ジョブを自前に固定 / 隠す / 自動に戻す" },
      { method: "GET", path: "/metrics", note: "Prometheus の公開形式 — ジョブ、runs、終了コード、プローブ" },
      { method: "GET", path: "/api/jobs", note: "オフラインの plist を含め、すべてのジョブを一覧" },
      { method: "GET", path: "/api/jobs/{label}", note: "単一ジョブのスナップショット（status、pid、runs、disabled）" },
      { method: "GET", path: "/api/alerts", note: "アプリごとの通知状態と、有効 / 無効の件数" },
      { method: "POST", path: "/api/alerts/{label}", note: '通知の切替: {"enabled": false}' },
      { method: "POST", path: "/api/alerts/{label}/test", note: "そのジョブのテスト通知を一通送る" },
      { method: "GET", path: "/api/settings/telegram", note: "トークンは保存済み？チャット ID は？トークン本体は返さない" },
      { method: "GET", path: "/api/jobs/{label}/logs?lines=200", note: "stdout と stderr を追尾（最大 10,000）" },
      { method: "GET", path: "/api/events", note: "SSE ストリーム — ジョブ一覧全体を 5 秒ごとに配信" },
      { method: "POST", path: "/api/jobs/{label}/reload", note: "launchctl bootout + bootstrap（読み取り専用モードでは 403）" },
    ],
  },
  steps: [
    {
      index: "01",
      title: "インストール",
      body: "Homebrew の cask でバイナリを入れるか、install-release.sh / install.sh で RunAtLoad + KeepAlive の LaunchAgent まで入れます。sudo 不要。スクリプトには --dry-run と --uninstall もあります。",
      command: "brew install --cask francistse/tap/deployboard",
    },
    {
      index: "02",
      title: "自分のアプリを指定する",
      body: "config.json の inventory.ours に名前空間を書くか、derive_roots にプロジェクトのフォルダを足して、plist のパスに分類させます。未分類のものは「その他」に出ます。UI でワンクリックすれば固定でき、config.json はホットリロードされます。",
      command: "open ~/.config/deployboard/config.json",
    },
    {
      index: "03",
      title: "見るか、スクレイプするか",
      body: "ダッシュボードは 127.0.0.1 で開きます。Prometheus から /metrics をスクレイプし、ベルでアプリごとの通知を切り替え、テーマをシステム、ライト、ダークから選べます。",
    },
  ],
  stats: [
    { value: "7", label: "状態の値", caption: "本家の六つ + disabled" },
    { value: "2s", label: "設定のホットリロード", caption: "再起動なしで新しいアプリを分類" },
    { value: "12", label: "Prometheus の系列ファミリー", caption: "ジョブ、runs、終了コード、プローブ" },
    { value: "127.0.0.1", label: "バインドする唯一のアドレス", caption: "クラウドなし、テレメトリなし、更新確認の通信なし" },
  ],
  faqSection: {
    eyebrow: "FAQ",
    title: "フォークなら、答えておくべき質問。",
    body: "本家とどういう関係か、も含みます。",
  },
  faqs: [
    {
      question: "フォーク元の launch-pilot と、何が違いますか？",
      answer:
        "本家ができることは、そのまま残しています。ジョブ表、ログの追尾、六つの診断、start/stop/reload です。Deployboard が足すのは、台帳ビュー（パス導出付きの自前 / その他 / ノイズ）、launchctl print による補強（runs と disabled）、Prometheus のエンドポイント、アプリごとに切り替えられる Telegram 通知、コマンド一つの macOS インストール、そして読み取り専用モードです。",
    },
    {
      question: "どのジョブが自分のものか、どうやって分かりますか？",
      answer:
        "規則は二つで、この順です。まず自分で書く許可リスト（inventory.ours）。次に導出です。plist のログパス、作業ディレクトリ、program、引数のいずれかが derive_roots に挙げたディレクトリの中にあれば、そのジョブは自分のものです。plist が指しているものはすべて証拠なので、推測もドメインの経験則も使いません。",
    },
    {
      question: "ジョブを間違えたらどうなりますか？",
      answer:
        "「その他」に出てきて、「未分類」と付きます。行から自動 / 自前 / 隠すを選べます。それが config.json に書き込まれ、サーバーは約 2 秒でホットリロードします。静かに隠すことはありません。launchd の全一覧は、常にチップ一つ先にあります。",
    },
    {
      question: "このうち何かが、自分のマシンの外に出ますか？",
      answer:
        "出ません。HTTP サーバーは 127.0.0.1 にだけバインドし、分析も電話ホームもありません。プロジェクト全体が外に出せる通信は、明示的に有効にした Telegram メッセージだけです。トークンは自分のキーチェーンにあります。",
    },
    {
      question: "通知なしで、メトリクスだけ使えますか？",
      answer:
        "使えます。通知の初期値は、自分のアプリではオン、それ以外ではオフです。アプリごと、カテゴリごと、または全体で止められます。/metrics と JSON API はそのまま動き、--read-only は変更を伴う呼び出しをすべて拒否します。",
    },
    {
      question: "なぜ plist を決して編集しないのですか？",
      answer:
        "意図的です。Deployboard は launchd の状態を読み、launchctl にラベルの start、stop、reload を頼めますが、ディスク上の plist は書き換えません。plist エディタが必要なら、定番の有料オプションは LaunchControl です。このツールが扱うのは、デプロイが何をしているかを知ることです。",
    },
  ],
  install: {
    eyebrow: "インストール",
    title: "コマンド一つ。設定ファイル一つ。タブ一つ。",
    body: "導入は3通りで同じバイナリ: Homebrew cask（ヒーローのコマンド）、Go なしで LaunchAgent まで入れる curl install-release.sh、クローンからの bash install.sh。sudo 不要。スクリプトは --dry-run と --uninstall 対応。",
  },
  cta: {
    eyebrow: "インストール",
    headline: "Mac が何を動かしているか、把握する。",
    body: "brew install --cask francistse/tap/deployboard — Homebrew がなければリリース用インストーラを curl。自分のものを伝える設定ファイルは一つ。",
    command: "brew install --cask francistse/tap/deployboard",
  },
  footer: {
    copyline: "© 2026 Deployboard — MIT ライセンス、RoboZephyr/launch-pilot のフォーク",
    links: [
      { label: "GitHub", href: REPO },
      { label: "本家", href: "https://github.com/RoboZephyr/launch-pilot" },
      { label: "メトリクスガイド", href: REPO + "/blob/main/docs/METRICS.md" },
      { label: "アラートガイド", href: REPO + "/blob/main/docs/ALERTS.md" },
      { label: "launchd(8)", href: "https://keith.github.io/xcode-man-pages/launchd.8.html" },
    ],
  },
};
