import type { Content } from "./types";
import { REPO, heroPanel, logStream, metricsQuery, metricsSample } from "./fixtures";

export const content: Content = {
  meta: {
    title: "Deployboard — 看你自己的 launchd 部署，而不是 500 個系統作業",
    description:
      "給你真正部署過的 launchd 作業用的本機儀表板：什麼在跑、什麼壞了、什麼是你刻意退役的，再加上 Prometheus 指標，以及可按應用程式開關的 Telegram 警報。只綁定 127.0.0.1；沒有雲端，沒有遙測。",
  },
  brand: {
    name: "Deployboard",
    mark: "DB",
    tagline: "你的 launchd 部署，一目了然",
    installCommand: "brew install --cask francistse/tap/deployboard",
    launchCommand: "deployboard",
    github: "github.com/francistse/deployboard",
    githubUrl: REPO,
    changelogUrl: REPO + "/blob/main/CHANGELOG.md",
    upstreamUrl: "https://github.com/RoboZephyr/launch-pilot",
    version: "v0.0.1",
    license: "MIT",
  },
  nav: [
    { label: "為何", href: "#why" },
    { label: "新增", href: "#ours" },
    { label: "指標", href: "#metrics" },
    { label: "警報", href: "#alerts" },
    { label: "安裝", href: "#install" },
  ],
  ui: {
    skipToContent: "跳至內容",
    github: "GitHub",
    copy: "複製",
    copied: "已複製",
    primaryNav: "主要",
    language: "語言",
    settings: "設定",
  },
  hero: {
    eyebrow: "v0.0.1 · MIT · macOS · fork 自 launch-pilot",
    headline: ["你的部署，", "不是 545 個系統作業。"],
    body: "你的 Mac 跑著幾百個 LaunchAgents——Dropbox、Chrome、Spotify，還有各種更新程式。Deployboard 只顯示你真正部署過的那些，告訴你哪些在跑、哪些壞了、哪些是你刻意退役的。然後把這一切變成 Prometheus 指標和 Telegram 警報。",
    primaryCta: { label: "一行指令安裝", href: "#install" },
    secondaryCta: { label: "閱讀原始碼", href: REPO },
    metaRow: [
      { key: "執行位置", value: "本機 · 只限 127.0.0.1" },
      { key: "顯示", value: "你的應用程式 · 系統雜訊隱藏" },
      { key: "提供", value: "/metrics · /api/jobs · SSE" },
    ],
  },
  livePanel: {
    title: "127.0.0.1:9410 · Deployboard",
    liveBadge: "SSE · 即時",
    appTagline: "macOS launchd 清單 — 只顯示你自己部署的",
    badges: {
      alerts: "16 開 · 2 關",
      inventory: "我的 16 · 其他 1 · 雜訊 528",
      writeMode: "寫入模式",
      url: "http://127.0.0.1:9410",
    },
    searchPlaceholder: "搜尋標籤…",
    noiseToggle: "顯示系統與廠商的工作",
    filters: { all: "全部", ours: "我的", noise: "雜訊", other: "其他" },
    hiddenSuffix: " 個已隱藏",
    columns: ["標籤", "PID", "結束", "重啟", "操作"],
    jobsSuffix: "項",
    nextRunPrefix: "下次 ·",
    retiredLabel: "⏹ 已退役 12 天",
    churnLabel: "↻ 頻繁重啟",
    restartLoopLabel: "⚠ 重啟迴圈",
    actions: { restart: "重啟", start: "啟動", enable: "啟用", logs: "日誌" },
    sourceLabels: { listed: "已列入", path: "自動（路徑）", unclassified: "未分類" },
    groupNames: { app: "範例應用", ops: "維運", infra: "基礎設施" },
    alertsOn: "Telegram 警報已開",
    alertsOff: "Telegram 警報已關",
    events: "GET /api/events",
    streamType: "text/event-stream",
    push: "每 5 秒推送",
    ...heroPanel,
  },
  why: {
    eyebrow: "為何",
    headline: "launchctl 列出全部，所以你什麼都看不見。",
    paragraphs: [
      "原有的工具回答「載入了什麼」，從不回答「我部署了什麼，它是否健康」。用使用者網域來篩也幫不上忙——一台在用的 Mac 上，看起來像「你的」作業，大多是 Dropbox、Google 的更新程式、Spotify、Tailscale，再加上一兩個瀏覽器輔助程式。那個重啟了 1,207 次的作業，就埋在正中間。",
      "Deployboard 從一份明確的清單出發：你自己控制的允許清單，再加上路徑推導——plist 的記錄路徑、工作目錄、program 或參數只要落在你的項目樹裡，那就是你的作業，自動算進去。其餘是系統自己的事，永遠只隔一下點擊，但不會擋在前面。",
    ],
    contrast: {
      before: {
        label: "沒有 Deployboard",
        bullets: [
          "launchctl list — 545 行，分不清哪些是你的",
          "悄悄重啟了 1,207 次的開發伺服器，看起來仍很健康",
          "你刻意停用的 plist，一直被當成失敗",
          "沒有歷史：「這算正常嗎？」沒有答案",
          "要等你偶然發現，才知道有東西已經死了",
        ],
      },
      after: {
        label: "有了 Deployboard",
        bullets: [
          "我的 / 其他 / 雜訊 — 預設先顯示你的部署",
          "來自 launchctl print 的 runs（重啟次數），超過閾值就標出",
          "disabled 是一種狀態，不是錯誤 — 退役就是退役",
          "Prometheus 的 /metrics，讓 Grafana 能顯示「從何時開始」",
          "狀態轉變時才發 Telegram 警報，按應用程式，帶冷卻時間",
        ],
      },
    },
  },
  statusSection: {
    eyebrow: "狀態",
    title: "七種狀態，其中一種的意思是「我把它退役了」。",
    body: "大多數工具把狀態收成 running / stopped / error，於是你幾個月前自己關掉的 plist，會永遠看起來像失敗。Deployboard 保留 launchd 真正區分的那些狀態，並讀取 launchctl print-disabled，讓意圖也成為答案的一部分。",
  },
  statusMeta: {
    running: "執行中",
    scheduled: "已排程",
    completed: "已完成",
    stopped: "已停止",
    error: "錯誤",
    offline: "離線",
    disabled: "已停用",
  },
  statuses: [
    { status: "running", rule: "PID > 0 — launchd print 同意它仍在運行" },
    { status: "scheduled", rule: "PID = 0、正常結束、已定義排程、沒有近期記錄" },
    { status: "completed", rule: "PID = 0、正常結束、記錄的 mtime 在 --recent-window 之內" },
    { status: "stopped", rule: "PID = 0、正常結束、沒有排程、沒有近期記錄" },
    { status: "error", rule: "上次結束狀態非零" },
    { status: "disabled", rule: "launchctl print-disabled 表示 disabled，沒有存活的 pid — 退役，不是壞掉" },
    { status: "offline", rule: "有 plist 檔案，但 launchctl list 不返回該 label" },
  ],
  forkSection: {
    eyebrow: "這個分叉加上的",
    title: "上游回答「載入了什麼」。這裡回答「我部署了什麼」。",
    body: "四項新增，全部建在 launchctl 自己的輸出上——不去猜一個作業屬於哪個廠商。",
    upstreamLabel: "上游仍然保留的部分",
    keepers: [
      { name: "記錄追蹤", body: "每個作業的 stdout 與 stderr，最多 10,000 行，可即時篩選。" },
      { name: "六項診斷", body: "結束碼、program 是否存在、program 可否執行、plist 擁有者、plist 權限、記錄路徑。" },
      { name: "SSE，不是輪詢", body: "GET /api/events 每 5 秒推送完整的作業清單。" },
      { name: "一按控制", body: "經 launchctl 做 start / stop / reload，並有確認對話框。" },
      { name: "JSON API", body: "與介面用的是同一面，有文件，curl 也好用。" },
      { name: "零依賴", body: "一個 Go 二進位檔，前端以 go:embed 內嵌，沒有常駐程式，沒有遙測。" },
    ],
  },
  forkAdditions: [
    {
      index: "01",
      title: "用 launchctl print，而不是 launchctl list。",
      body: "launchctl list 沒有重啟次數，也沒有 disabled 旗標。Deployboard 用 launchctl print 讀 runs 和 pid，用 launchctl print-disabled 讀意圖——於是抖動看得見，刻意退役的作業也不再看起來像壞掉。",
      accent: "brand",
    },
    {
      index: "02",
      title: "清單由你決定。",
      body: "我的 / 其他 / 雜訊，每一行都有出處（已列入、自動（路徑）、未分類）。分類控制會寫回 config.json，大約 2 秒內即時重新載入——教它一個新應用程式，不必重啟。",
    },
    {
      index: "03",
      title: "給 launchd 的 Prometheus 指標。",
      body: "deployboard_job_up、_runs、_last_exit_code、_disabled，再加上 IPv4/IPv6 連接埠探測。儀表板只能告訴你「現在停了」；時間序列能告訴你「03:10 開始抖動」。",
      accent: "accent",
    },
    {
      index: "04",
      title: "可按應用程式開關的 Telegram 警報。",
      body: "只在狀態轉變時通知——error、offline、連接埠無法連線、重啟風暴，以及復原——並有按應用程式的開關、冷卻時間、靜音時段。bot token 放在 macOS 鑰匙圈，永不寫進檔案。",
      accent: "warning",
    },
  ],
  logStream,
  stream: {
    eyebrow: "即時串流",
    headline: "launchd 一寫下記錄，瀏覽器就收到。",
    body: "每個作業的 stdout 和 stderr，從 plist 聲明的路徑追下去，經 Server-Sent Events 推送。沒有連接埠、也沒有 HTTP 面的作業一樣會追蹤——有 cron 排程的收集器，即使沒有東西可探測，仍是清單的一部分。",
    badges: ["Server-Sent Events", "逐個作業追蹤", "最多 10,000 行", "即時篩選"],
    endpoint: "GET /api/events",
    endpointStatus: "串流中",
  },
  metrics: {
    eyebrow: "指標",
    headline: "這個領域裡，唯一的 launchd exporter。",
    body: "把 Prometheus 指到介面用的同一個連接埠。標籤基數有界，省略是誠實的（從未結束的作業沒有 last-exit 序列），只有暴露了連接埠的作業才有 probe 序列——探測也會試 IPv6 的 ::1，因為有些開發伺服器只綁在那裡。",
    sampleLabel: "GET /metrics",
    queryLabel: "promql",
    footnoteBefore:
      "從提供介面的同一個行程擷取即可，不必另外部署 exporter，也不需要 sidecar。沒有的序列就省略，不會造假：從未結束的作業不會有 ",
    footnoteCode: "last_exit",
    footnoteAfter: " 行，沒有連接埠的作業也不會有 probe 行。",
    sample: metricsSample,
    query: metricsQuery,
  },
  alerts: {
    eyebrow: "警報",
    headline: "它會在 Telegram 通知你，而且只說一次。",
    body: "按狀態轉變來發，所以一個來回抖動的作業不能洗版：壞掉時一則，若持續重啟則一則受速率限制的，恢復時再一則。復原訊息永不被靜音時段壓掉。bot token 放在 macOS 鑰匙圈，由儀表板自己寫入——永不進檔案，永不進記錄行，也永不回到頁面上。",
    channel: "telegram · deployboard",
    triggerHeader: "觸發",
    kindHeader: "種類",
    footer: "按應用程式的開關、冷卻時間、靜音時段，以及靜音時段永不吞掉的復原訊息。",
    message: [
      "🔴 RUN_STORM",
      "Example App · com.example.app.web",
      "狀態: 執行中",
      "重啟: 1207",
      "2026-10-03 10:41:07 +0800",
    ],
    rules: [
      { trigger: "狀態變為 error", kind: "error" },
      { trigger: "有 plist，但未載入", kind: "offline" },
      { trigger: "連接埠不再回應", kind: "unreachable" },
      { trigger: "每輪掃描之間 runs +25", kind: "run_storm" },
      { trigger: "回到 running", kind: "recovery" },
    ],
  },
  api: {
    eyebrow: "API",
    title: "介面用到的一切，你的腳本也能用。",
    body: "Web 介面是 /api/jobs 和 /api/events 的一個消費者。curl 也是。綁定伺服器，指向端點，解析 JSON。",
    verb: "方法",
    path: "路徑",
    description: "說明",
    endpoints: [
      { method: "GET", path: "/api/inventory", note: "類別與群組計數，以及每個作業如何被分類" },
      { method: "POST", path: "/api/inventory/classify", note: "把作業釘選為我的 / 隱藏 / 回到自動" },
      { method: "GET", path: "/metrics", note: "Prometheus 文本格式 — 作業、runs、結束碼、探測" },
      { method: "GET", path: "/api/jobs", note: "列出每個作業，包括離線的 plist" },
      { method: "GET", path: "/api/jobs/{label}", note: "單一作業快照（status、pid、runs、disabled）" },
      { method: "GET", path: "/api/alerts", note: "按應用程式的警報狀態，以及已啟用 / 已停用計數" },
      { method: "POST", path: "/api/alerts/{label}", note: '切換警報: {"enabled": false}' },
      { method: "POST", path: "/api/alerts/{label}/test", note: "為該作業發送一則測試警報" },
      { method: "GET", path: "/api/settings/telegram", note: "已儲存 token？有 chat id？——永不回傳 token 本身" },
      { method: "GET", path: "/api/jobs/{label}/logs?lines=200", note: "追蹤 stdout 與 stderr（最多 10,000）" },
      { method: "GET", path: "/api/events", note: "SSE 串流 — 每 5 秒推送完整作業清單" },
      { method: "POST", path: "/api/jobs/{label}/reload", note: "launchctl bootout + bootstrap（唯讀模式回 403）" },
    ],
  },
  steps: [
    {
      index: "01",
      title: "安裝",
      body: "用 Homebrew cask 安裝二進位檔，或用 install-release.sh / install.sh 一併寫入帶 RunAtLoad + KeepAlive 的 LaunchAgent。不用 sudo；腳本支援 --dry-run 與 --uninstall。",
      command: "brew install --cask francistse/tap/deployboard",
    },
    {
      index: "02",
      title: "指向你的應用程式",
      body: "你可以在 config.json 的 inventory.ours 下列出命名空間，也可以把項目資料夾加進 derive_roots，讓 plist 路徑自己分類。未分類的會出現在「其他」——在介面按一下就釘選，config.json 會即時重新載入。",
      command: "open ~/.config/deployboard/config.json",
    },
    {
      index: "03",
      title: "看著它，或擷取它",
      body: "儀表板在 127.0.0.1 打開。用 Prometheus 擷取 /metrics，用鈴鐺按應用程式開關警報，並在系統、淺色、深色之間切換外觀。",
    },
  ],
  stats: [
    { value: "7", label: "狀態值", caption: "上游六個 + disabled" },
    { value: "2s", label: "設定即時重新載入", caption: "不必重啟就能分類新應用程式" },
    { value: "12", label: "Prometheus 序列家族", caption: "作業、runs、結束碼、探測" },
    { value: "127.0.0.1", label: "唯一綁定的地址", caption: "沒有雲端、沒有遙測、沒有更新探測" },
  ],
  faqSection: {
    eyebrow: "FAQ",
    title: "一個分叉必須回答的問題。",
    body: "包括它和上游是什麼關係。",
  },
  faqs: [
    {
      question: "它和所分叉的 launch-pilot 有何不同？",
      answer:
        "上游做的事都還在——作業表、記錄追蹤、六項診斷、start/stop/reload。Deployboard 加上清單視圖（我的 / 其他 / 雜訊，帶路徑推導）、launchctl print 的補充（runs 和 disabled）、Prometheus 端點、可按應用程式開關的 Telegram 警報、一行指令的 macOS 安裝，以及唯讀模式。",
    },
    {
      question: "它怎麼知道哪些作業是我的？",
      answer:
        "兩條規則，按順序：先是你寫下的允許清單（inventory.ours），然後是推導——如果 plist 的記錄路徑、工作目錄、program 或參數落在你列於 derive_roots 的目錄裡，那就是你的作業。plist 指向的一切都是證據，所以沒有猜測，也沒有網域的經驗法則。",
    },
    {
      question: "如果它把一個作業判錯了呢？",
      answer:
        "它會出現在「其他」，標成「未分類」，你在該行選擇自動 / 我的 / 隱藏。這會寫入 config.json，伺服器大約兩秒內即時重新載入。沒有東西會被悄悄藏起：完整的 launchd 清單永遠只隔一個標籤。",
    },
    {
      question: "這些東西會離開我的機器嗎？",
      answer:
        "不會。HTTP 伺服器只綁定 127.0.0.1，沒有分析追蹤，也不會回報。整個項目唯一能打出去的，是你明確開啟的 Telegram 訊息——用的 token 存在你自己的鑰匙圈裡。",
    },
    {
      question: "可以只用指標、不要警報嗎？",
      answer:
        "可以。警報預設對你自己的應用程式開啟，對其餘的關閉；可以按應用程式、按類別，或整個關掉。/metrics 和 JSON API 照樣可用，而 --read-only 會拒絕每一次會改動狀態的呼叫。",
    },
    {
      question: "為什麼它從不修改我的 plist？",
      answer:
        "故意的。Deployboard 讀取 launchd 狀態，也可以請 launchctl 對一個 label 做 start、stop 或 reload，但不會改寫磁碟上的 plist。若你要的是 plist 編輯器，LaunchControl 是既有的付費選擇；這個工具關心的是，你的部署正在做什麼。",
    },
  ],
  install: {
    eyebrow: "安裝",
    title: "一行指令。一個設定檔。一個分頁。",
    body: "二進位檔優先用 Homebrew；需要 LaunchAgent 時用 install-release.sh / install.sh——重新開機或當機之後儀表板會自己回來。不用 sudo，可重複執行，包含 --dry-run 和 --uninstall。",
  },
  cta: {
    eyebrow: "安裝",
    headline: "弄清楚你的 Mac 在跑什麼。",
    body: "一行指令安裝，一個設定檔告訴它什麼是你的，下一次有東西在背景悄悄開始自我重啟時，Telegram 會來一則訊息。",
    command: "brew install --cask francistse/tap/deployboard",
  },
  footer: {
    copyline: "© 2026 Deployboard — MIT 授權，分叉自 RoboZephyr/launch-pilot",
    links: [
      { label: "GitHub", href: REPO },
      { label: "上游", href: "https://github.com/RoboZephyr/launch-pilot" },
      { label: "指標指南", href: REPO + "/blob/main/docs/METRICS.md" },
      { label: "警報指南", href: REPO + "/blob/main/docs/ALERTS.md" },
      { label: "launchd(8)", href: "https://keith.github.io/xcode-man-pages/launchd.8.html" },
    ],
  },
};
